require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'doc/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Exclude:
    - config/**/*
    - spec/**/*
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
Performance/AncestorsInclude:
  Enabled: true
Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true
Performance/BigDecimalWithNumericArgument:
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
Rails/WhereExists:
  Enabled: true
Rails/WhereNot:
  Enabled: true
RSpec/Capybara/FeatureMethods:
  Enabled: true
  Exclude:
    - spec/system/**/*
# We use expect in before hooks to validate contexts & scenarios
RSpec/ExpectInHook:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: true
  Exclude:
    - spec/system/**/*
RSpec/NestedGroups:
  Enabled: true
  Max: 4
Style/ArgumentsForwarding:
  Enabled: true
Style/BlockComments:
  Enabled: true
  Exclude:
    - spec/**/*
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*
Style/CollectionCompact:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: true
# TODO: Enable for Ruby 3.0 upgrade
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/NegatedIfElseCondition:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/StringLiterals:
  Enabled: false
Style/SwapValues:
  Enabled: true