development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cincirb_production

staging:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: cincirb_staging
