#!/bin/sh

set -e

echo ""
echo "Setting up cincyrb"
echo ""

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies with Bundler."
bundle install --without production --local --path vendor

#
# Setting up .env file for Meetup info
#
if test -f .env; then
  echo "  + Creating .env"
else
  echo "  + .env exists, good."
  cp .env.sample .env
fi

#
# Set up the database
#
echo "  + Creating the development database."
bundle exec rake db:setup
bundle exec rake db:migrate

#
# Now what?
#
echo "  Ok, setup complete. To start the application, run"
echo "    rails server"
